apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: redis-cluster
spec:
  compositeTypeRef:
    apiVersion: redis.example.io/v1alpha1
    kind: XRedisCluster
  resources:
    - name: subscription
      base:
        apiVersion: rediscloud.redis.com/v1alpha1
        kind: Subscription
        spec:
          forProvider:
            name: redis-cluster-subscription
            cloudProvider:
              - provider: AWS
                cloudAccountId: 1
                region:
                  - region: us-east-1
                    networkingDeploymentCidr: 10.0.0.0/24
                    preferredAvailabilityZones:
                      - us-east-1a
                      - us-east-1b
            database:
              - name: redis-cluster-db
                protocol: redis
                memoryLimitInGb: 1
                dataPersistence: aof-every-1-second
                throughputMeasurement:
                  by: operations-per-second
                  value: 10000
                replication: true
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.cloudProvider[0].region[0].region"
        - fromFieldPath: "spec.parameters.memoryGb"
          toFieldPath: "spec.forProvider.database[0].memoryLimitInGb"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.name"
          transforms:
            - type: string
              string:
                fmt: "%s-subscription"
    
    - name: database
      base:
        apiVersion: rediscloud.redis.com/v1alpha1
        kind: SubscriptionDatabase
        spec:
          forProvider:
            subscriptionIdSelector:
              matchControllerRef: true
            protocol: redis
            dataPersistence: aof-every-1-second
            replication: true
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.name"
          transforms:
            - type: string
              string:
                fmt: "%s-database"
        - fromFieldPath: "spec.parameters.memoryGb"
          toFieldPath: "spec.forProvider.memoryLimitInGb"
        - fromFieldPath: "spec.parameters.throughput"
          toFieldPath: "spec.forProvider.throughputMeasurement.value"