apiVersion: essentials.redis.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: essentials/v1alpha1/database
  labels:
    testing.upbound.io/example-name: database-resource
  name: database-resource
spec:
  forProvider:
    alert:
    - name: throughput-higher-than
      value: 80
    dataPersistence: none
    enableDefaultUser: true
    name: database-name
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    replication: false
    subscriptionId: ${rediscloud_essentials_subscription.subscription-resource.id}
    tags:
      env: dev
      priority: "2"

---

apiVersion: essentials.redis.io/v1alpha1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: essentials/v1alpha1/database
  labels:
    testing.upbound.io/example-name: subscription-resource
  name: subscription-resource
spec:
  forProvider:
    name: subscription-name
    paymentMethodId: ${data.rediscloud_payment_method.card.id}
    planId: ${data.rediscloud_essentials_plan.plan.id}
