apiVersion: essentials.redis.io/v1alpha1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: essentials/v1alpha1/subscription
  labels:
    testing.upbound.io/example-name: subscription-resource
  name: subscription-resource
spec:
  forProvider:
    name: subscription-name
    paymentMethodId: ${data.rediscloud_payment_method.card.id}
    planId: ${data.rediscloud_essentials_plan.plan.id}
