apiVersion: active.redis.io/v1alpha1
kind: ActiveSubscription
metadata:
  annotations:
    meta.upbound.io/example-id: active/v1alpha1/activesubscription
  labels:
    testing.upbound.io/example-name: subscription-resource
  name: subscription-resource
spec:
  forProvider:
    cloudProvider: AWS
    creationPlan:
    - datasetSizeInGb: 1
      modules:
      - RedisJSON
      quantity: 1
      region:
      - networkingDeploymentCidr: 192.168.0.0/24
        readOperationsPerSecond: 1000
        region: us-east-1
        writeOperationsPerSecond: 1000
      - networkingDeploymentCidr: 10.0.1.0/24
        readOperationsPerSecond: 1000
        region: us-east-2
        writeOperationsPerSecond: 1000
    name: subscription-name
    paymentMethodId: ${data.rediscloud_payment_method.card.id}
