apiVersion: rediscloud.redis.io/v1alpha1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: rediscloud/v1alpha1/subscription
  labels:
    testing.upbound.io/example-name: subscription-resource
  name: subscription-resource
spec:
  forProvider:
    cloudProvider:
    - provider: ${data.rediscloud_cloud_account.account.provider_type}
      region:
      - multipleAvailabilityZones: true
        networkingDeploymentCidr: 10.0.0.0/24
        preferredAvailabilityZones:
        - euw1-az1
        - euw1-az2
        - euw1-az3
        region: eu-west-1
    creationPlan:
    - datasetSizeInGb: 15
      modules:
      - RedisJSON
      quantity: 1
      replication: true
      throughputMeasurementBy: operations-per-second
      throughputMeasurementValue: 20000
    maintenanceWindows:
    - mode: manual
      window:
      - days:
        - Tuesday
        - Friday
        durationInHours: 8
        startHour: 22
    memoryStorage: ram
    name: subscription-name
    paymentMethod: credit-card
    paymentMethodId: ${data.rediscloud_payment_method.card.id}
    redisVersion: "7.2"
