apiVersion: acl.redis.io/v1alpha1
kind: Rule
metadata:
  annotations:
    meta.upbound.io/example-id: acl/v1alpha1/rule
  labels:
    testing.upbound.io/example-name: rule-resource
  name: rule-resource
spec:
  forProvider:
    name: my-rule
    rule: +@read ~cache:*
