apiVersion: acl.redis.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: acl/v1alpha1/user
  labels:
    testing.upbound.io/example-name: user-resource
  name: user-resource
spec:
  forProvider:
    name: my-user
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    role: my-role
