apiVersion: private.redis.io/v1alpha1
kind: ServiceConnect
metadata:
  annotations:
    meta.upbound.io/example-id: private/v1alpha1/serviceconnect
  labels:
    testing.upbound.io/example-name: service
  name: service
spec:
  forProvider:
    subscriptionId: ${rediscloud_subscription.subscription.id}

---

apiVersion: rediscloud.redis.io/v1alpha1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: private/v1alpha1/serviceconnect
  labels:
    testing.upbound.io/example-name: subscription
  name: subscription
spec:
  forProvider:
    cloudProvider:
    - provider: GCP
      region:
      - networkingDeploymentCidr: 10.0.1.0/24
        region: ${var.gcp_region}
    creationPlan:
    - datasetSizeInGb: 15
      quantity: 1
      replication: true
      throughputMeasurementBy: operations-per-second
      throughputMeasurementValue: 20000
    name: subscription-name
    paymentMethodId: ${data.rediscloud_payment_method.card.id}
